### ISSUE TITLE
Zusammenhang Access / MySQL

### ISSUE THREAD

**Issue by IchLiebeEistee** [IchLiebeEistee/I2_Webuserinterface_Datenbankverwaltung#21]
Es ist wichtig, den Zusammenhang zwischen der Access- und der MySQL-Datenbank zu verstehen, um das System später überführen zu können. Dabei kann uns auch Raphael helfen.

**Comment by Pandigov** [comment]
Müssen Raphael dafür fragen. Alleine können wir das gar nicht herausfinden glaube ich
