### ISSUE TITLE
Inaktiv:  Möglichkeiten zum Bearbeiten und Anlegen der Fakultäten

### ISSUE THREAD

**Issue by mpeeps02** [IchLiebeEistee/I2_Webuserinterface_Datenbankverwaltung#37]
Unter dem Reiter Fakultäten auf der Website (oben links) soll die  Möglichkeit zum Bearbeiten und Anlegen von Fakultäten implementiert werden. 

Neu Anlegen: mein Vorschlag
- Button Fakultät hinzufügen implementieren, dass kann beispielsweise ein Popup-Fenster erscheinen vgl. Hochschule hinzufügen auf Mainpage
- noch unklar, was für Informationen dort gespeichert werden sollen !!!
Bearbeiten: mein Vorschlag
- Button Bearbeiten hinter einzelnen Fakultäten implementieren und ebenfalls Popup-Fenster mit Informationen anzeigen
- Löschfunktion noch unklar!!!

Das sind nur meine Vorschläge, Ihr könnt gerne es so gestalten wie es euch intuitiv besser gefällt.

**Comment by Kevin-Freund** [comment]
@mpeeps02 bitte dieses Issue löschen
