### ISSUE TITLE
Entwicklerdokumentation (aufgeteielt)

### ISSUE THREAD

**Issue by mpeeps02** [IchLiebeEistee/I2_Webuserinterface_Datenbankverwaltung#39]
Es muss die Entwicklerdokumentation in unserem Beleg beschrieben werden. Vergleich siehe Projektgruppe I3.
Inhalte:
- Design
- Softwaredokumentation

Dies ist sehr viel Arbeit, mindestens zu zweit bearbeiten.

**Comment by mpeeps02** [comment]
Ich habe das jetzt mal in zwei Teile geteilt.

**Comment by Kevin-Freund** [comment]
gesplittet in #40 und #41
Aktuelle Issue wird daher geschlossen, der Organisation zuliebe.

**Comment by Kevin-Freund** [comment]
@mpeeps02 bitte dieses Issue löschen
