### ISSUE TITLE
Erfassen von Stakeholdern

### ISSUE THREAD

**Issue by IchLiebeEistee** [IchLiebeEistee/I2_Webuserinterface_Datenbankverwaltung#6]
Für unser Vision müssen wir Stakeholder erfassen und diese beschreiben. Außerdem muss die Benutzerumgebung beschrieben werden.

**Comment by Kevin-Freund** [comment]
siehe Commit 671675f2d9ae4935c74858cb3dc1c0d20ae9bf00
