### ISSUE TITLE
Erweiterung der Hauptfunktion und Anforderungen

### ISSUE THREAD

**Issue by IchLiebeEistee** [IchLiebeEistee/I2_Webuserinterface_Datenbankverwaltung#8]
Nach dem treffen mit der Stabsstelle sind neue Anforderungen entstanden. Diese müssen protokoliert werden. Da Marlene und Dilara bei dem Treffen anwesend waren. würde ich vorschlagen, dass sie Kevin unterstützen.

**Comment by Kevin-Freund** [comment]
siehe Commit 3995cbc6b6033a88e26f5bba6bd0fc6b6a16088b
